import type { Task, User } from "./types"

export const mockUsers: User[] = [
  { id: "1", name: "דנה כהן", email: "dana@insurance.co.il", password: "123456", avatar: "/woman-with-brown-hair-professional.jpg", role: "admin" },
  { id: "2", name: "יוסי לוי", email: "yossi@insurance.co.il", password: "123456", avatar: "/professional-man-glasses.png", role: "user" },
  { id: "3", name: "מיכל אברהם", email: "michal@insurance.co.il", password: "123456", avatar: "/professional-blonde-woman.png", role: "admin" },
  { id: "4", name: "אלון שמיר", email: "alon@insurance.co.il", password: "123456", avatar: "/man-beard-professional.jpg", role: "user" },
]

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "עיצוב דף הבית החדש",
    description: "יצירת עיצוב מודרני לדף הבית של האתר עם דגש על חווית משתמש",
    column: "in-progress",
    status: "in-progress",
    priority: "high",
    dueDate: new Date("2026-01-20"),
    assigneeId: "3",
    assigneeName: "מיכל אברהם",
    assigneeAvatar: "/professional-blonde-woman.png",
    handlerId: "3",
    handlerName: "מיכל אברהם",
    handlerAvatar: "/professional-blonde-woman.png",
    inProgressStation: "design",
    stationNote: "עובדת על מוקאפים בפיגמה",
    taggedUserIds: ["1", "2"],
    figmaLink: "https://www.figma.com/design/example123",
    processSpecLink: "https://docs.google.com/document/d/example123",
    files: [
      { id: "f1", name: "brief.pdf", type: "pdf", url: "#", uploadedAt: new Date("2026-01-10"), uploadedBy: "1" },
    ],
    comments: [
      {
        id: "c1",
        content: "אני מתחילה לעבוד על זה היום",
        authorId: "3",
        authorName: "מיכל אברהם",
        createdAt: new Date("2026-01-11"),
      },
    ],
    history: [
      { id: "h1", action: "created", userId: "1", userName: "דנה כהן", timestamp: new Date("2026-01-10") },
      {
        id: "h2",
        action: "updated",
        field: "status",
        oldValue: "todo",
        newValue: "in-progress",
        userId: "3",
        userName: "מיכל אברהם",
        timestamp: new Date("2026-01-11"),
      },
      {
        id: "h2b",
        action: "station_changed",
        field: "inProgressStation",
        stationTo: "design",
        userId: "3",
        userName: "מיכל אברהם",
        timestamp: new Date("2026-01-11"),
      },
    ],
    createdAt: new Date("2026-01-10"),
    createdBy: "1",
    updatedAt: new Date("2026-01-11"),
    order: 1,
  },
  {
    id: "2",
    title: "כתיבת תוכן לעמוד השירותים",
    description: "הכנת תוכן מקצועי לעמוד השירותים החדש",
    column: "todo",
    status: "todo",
    priority: "medium",
    dueDate: new Date("2026-01-25"),
    assigneeId: "2",
    assigneeName: "יוסי לוי",
    assigneeAvatar: "/professional-man-glasses.png",
    handlerId: null,
    handlerName: null,
    handlerAvatar: null,
    taggedUserIds: [],
    files: [],
    comments: [],
    history: [{ id: "h3", action: "created", userId: "1", userName: "דנה כהן", timestamp: new Date("2026-01-12") }],
    createdAt: new Date("2026-01-12"),
    createdBy: "1",
    updatedAt: new Date("2026-01-12"),
    order: 1,
  },
  {
    id: "3",
    title: "בדיקת תאימות מובייל",
    description: "וידוא שכל העמודים מוצגים כראוי במכשירים ניידים",
    column: "done",
    status: "done",
    priority: "low",
    dueDate: new Date("2026-01-15"),
    assigneeId: "4",
    assigneeName: "אלון שמיר",
    assigneeAvatar: "/man-beard-professional.jpg",
    handlerId: "4",
    handlerName: "אלון שמיר",
    handlerAvatar: "/man-beard-professional.jpg",
    taggedUserIds: ["1"],
    files: [
      {
        id: "f2",
        name: "test-results.xlsx",
        type: "excel",
        url: "#",
        uploadedAt: new Date("2026-01-14"),
        uploadedBy: "4",
      },
    ],
    comments: [
      {
        id: "c2",
        content: "הכל עובד מעולה!",
        authorId: "4",
        authorName: "אלון שמיר",
        createdAt: new Date("2026-01-15"),
      },
    ],
    history: [
      { id: "h4", action: "created", userId: "1", userName: "דנה כהן", timestamp: new Date("2026-01-08") },
      {
        id: "h5",
        action: "updated",
        field: "status",
        oldValue: "in-progress",
        newValue: "done",
        userId: "4",
        userName: "אלון שמיר",
        timestamp: new Date("2026-01-15"),
      },
    ],
    createdAt: new Date("2026-01-08"),
    createdBy: "1",
    updatedAt: new Date("2026-01-15"),
    order: 1,
  },
  {
    id: "4",
    title: "אינטגרציה עם מערכת CRM",
    description: "חיבור האתר למערכת ניהול הלקוחות הקיימת",
    column: "in-progress",
    status: "on-hold",
    priority: "high",
    dueDate: new Date("2026-01-30"),
    assigneeId: "4",
    assigneeName: "אלון שמיר",
    assigneeAvatar: "/man-beard-professional.jpg",
    handlerId: "4",
    handlerName: "אלון שמיר",
    handlerAvatar: "/man-beard-professional.jpg",
    inProgressStation: "development",
    stationNote: "ממתינים לפרטי גישה מספק ה-CRM",
    taggedUserIds: ["1", "2"],
    processSpecLink: "https://docs.google.com/document/d/crm-integration-spec",
    files: [],
    comments: [
      {
        id: "c4",
        content: "ממתינים לפרטי גישה מספק ה-CRM",
        authorId: "4",
        authorName: "אלון שמיר",
        createdAt: new Date("2026-01-13"),
      },
    ],
    history: [{ id: "h6", action: "created", userId: "1", userName: "דנה כהן", timestamp: new Date("2026-01-13") }],
    createdAt: new Date("2026-01-13"),
    createdBy: "1",
    updatedAt: new Date("2026-01-13"),
    order: 2,
  },
  {
    id: "5",
    title: "עדכון לוגו החברה",
    description: "רענון הלוגו בהתאם לברנדינג החדש",
    column: "in-progress",
    status: "qa",
    priority: "medium",
    dueDate: new Date("2026-01-18"),
    assigneeId: "3",
    assigneeName: "מיכל אברהם",
    assigneeAvatar: "/professional-blonde-woman.png",
    handlerId: "1",
    handlerName: "דנה כהן",
    handlerAvatar: "/woman-with-brown-hair-professional.jpg",
    inProgressStation: "business-review",
    stationNote: "מחכים לאישור סופי מהנהלה",
    taggedUserIds: ["1"],
    figmaLink: "https://www.figma.com/design/logo456",
    files: [],
    comments: [
      {
        id: "c3",
        content: "יש לי כמה גרסאות מוכנות, ממתינה לאישור",
        authorId: "3",
        authorName: "מיכל אברהם",
        createdAt: new Date("2026-01-13"),
      },
    ],
    history: [
      { id: "h7", action: "created", userId: "1", userName: "דנה כהן", timestamp: new Date("2026-01-10") },
      {
        id: "h8",
        action: "updated",
        field: "status",
        oldValue: "in-progress",
        newValue: "review",
        userId: "3",
        userName: "מיכל אברהם",
        timestamp: new Date("2026-01-12"),
      },
      {
        id: "h8b",
        action: "station_changed",
        field: "inProgressStation",
        stationFrom: "design",
        stationTo: "business-review",
        userId: "1",
        userName: "דנה כהן",
        timestamp: new Date("2026-01-13"),
      },
    ],
    createdAt: new Date("2026-01-10"),
    createdBy: "1",
    updatedAt: new Date("2026-01-12"),
    order: 3,
  },
  {
    id: "6",
    title: "שדרוג אבטחת האתר",
    description: "התקנת תעודת SSL ועדכון הגדרות אבטחה",
    column: "in-progress",
    status: "on-hold",
    priority: "high",
    dueDate: new Date("2026-02-01"),
    assigneeId: "4",
    assigneeName: "אלון שמיר",
    assigneeAvatar: "/man-beard-professional.jpg",
    handlerId: "2",
    handlerName: "יוסי לוי",
    handlerAvatar: "/professional-man-glasses.png",
    inProgressStation: "testing",
    stationNote: "בדיקת תצורת האבטחה",
    taggedUserIds: [],
    files: [],
    comments: [],
    history: [
      { id: "h9", action: "created", userId: "1", userName: "דנה כהן", timestamp: new Date("2026-01-14") },
      {
        id: "h9b",
        action: "handler_changed",
        field: "handlerId",
        newValue: "יוסי לוי",
        userId: "1",
        userName: "דנה כהן",
        timestamp: new Date("2026-01-15"),
      },
    ],
    createdAt: new Date("2026-01-14"),
    createdBy: "1",
    updatedAt: new Date("2026-01-14"),
    order: 4,
  },
]
